environment: "Curved Gridroom"
spawn_height: 0.50

drones:
  - id: 0
    x: 0.0
    y: 0.0
    yaw: 0.0
    stereo_camera: true
    arm: true
    arm_type: "5dof"
    px4_autolaunch: true
    px4_vehicle_id: 0
